package token

type TokenType string

type Token struct {
	Type    TokenType
	Literal string
}

const (
	ILLEGAL = "ILLEGAL"
	EOF     = "EOF"

	// 7.2.3 Identifiers
	IDENTIFIER = "IDENTIFIER"

	// 7.2.4  Keywords
	ABSTRACT    = "abstract"
	ANY         = "any"
	ALIAS       = "alias"
	ATTRIBUTE   = "attribute"
	BITFIELD    = "bitfield"
	BITMASK     = "bitmask"
	BITSET      = "bitset"
	BOOLEAN     = "boolean"
	CASE        = "case"
	CHAR        = "char"
	COMPONENT   = "component"
	CONNECTOR   = "connector"
	CONST       = "const"
	CONSUMES    = "consumes"
	CONTEXT     = "context"
	CUSTOM      = "custom"
	DEFAULT     = "default"
	DOUBLE      = "double"
	EXCEPTION   = "exception"
	EMITS       = "emits"
	ENUM        = "enum"
	EVENTTYPE   = "eventtype"
	FACTORY     = "factory"
	FALSE       = "FALSE"
	FINDER      = "finder"
	FIXED       = "fixed"
	FLOAT       = "float"
	GETRAISES   = "getraises"
	HOME        = "home"
	IMPORT      = "import"
	IN          = "in"
	INOUT       = "inout"
	INTERFACE   = "interface"
	LOCAL       = "local"
	LONG        = "long"
	MANAGES     = "manages"
	MAP         = "map"
	MIRRORPORT  = "mirrorport"
	MODULE      = "module"
	MULTIPLE    = "multiple"
	NATIVE      = "native"
	OBJECT      = "object"
	OCTET       = "octet"
	ONEWAY      = "oneway"
	OUT         = "out"
	PRIMARYKEY  = "primarykey"
	PRIVATE     = "private"
	PORT        = "port"
	PORTTYPE    = "porttype"
	PROVIDES    = "provides"
	PUBLIC      = "public"
	PUBLISHES   = "publishes"
	RAISES      = "raises"
	READONLY    = "readonly"
	SETRAISES   = "setraises"
	SEQUENCE    = "sequence"
	SHORT       = "short"
	STRING      = "string"
	STRUCT      = "struct"
	SUPPORTS    = "supports"
	SWITCH      = "switch"
	TRUE        = "TRUE"
	TRUNCATABLE = "trucatable"
	TYPEDEF     = "typedef"
	TYPEID      = "typeid"
	TYPENAME    = "typename"
	TYPEPREFIX  = "typeprefix"
	UNSIGNED    = "unsigned"
	UNION       = "union"
	USES        = "uses"
	VALUEBASE   = "ValueBase"
	VALUETYPE   = "valuetype"
	VOID        = "void"
	WCHAR       = "wchar"
	WSTRING     = "wstring"
	INT8        = "int8"
	UINT8       = "uint8"
	INT16       = "int16"
	INT32       = "int32"
	INT64       = "int64"
	UINT16      = "uint16"
	UINT32      = "unit32"
	UINT64      = "unit64"

	// 7.2.5 - Punctation
	SEMICOLON   = ";"
	LCURLY      = "{"
	RCURLY      = "}"
	COLON       = ":"
	COMMA       = ","
	EQUALS      = "="
	PLUS        = "+"
	MINUS       = "-"
	LPAREN      = "("
	RPAREN      = ")"
	LT          = "<"
	GT          = ">"
	LBRACKET    = "["
	RBRACKET    = "]"
	SINGLEQUOTE = "'"
	DOUBLEQUOTE = "\""
	BACKSLASH   = "\\"
	VERTBAR     = "|"
	CARET       = "^"
	AMPERSAND   = "&"
	ASTERISK    = "*"
	SLASH       = "/"
	PERCENT     = "%"
	TILDE       = "~"
	AT          = "@"
)
